# Run only on PRs and the master branch
branches:
  only:
    - master

# Default to use the container infrastructure
dist: trusty
sudo: false

# Chttps://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
cache:
  - cargo
  - bundler

# Set the default language to rust
# https://docs.travis-ci.com/user/languages/rust/
language: rust

# Since the delivery-cli ships in the ChefDK, we use the ChefDK as a base
# ruby to ensure everything works appropriately.
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

env:
  global:
  - HOME="/home/travis"
  - USE_CHEFDK_LIBS=true

# Don't let failures in non-required versions block us
matrix:
  include:
  - env:
      CUCUMBER_TESTS: 1
    rust: 1.26.0
    before_install:
    - rvm install 2.5.1
    script:
    - bundle install
    - bundle exec cucumber
  - env: 
      CARGO_TESTS_STABLE: 1
    rust: stable
    script: make test
    install:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - env:
      CARGO_TESTS_BETA: 1
    rust: beta
    script: make test
    install:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - env: 
      CARGO_TESTS_DEFINED: 1
    rust: 1.26.0
    script: make test
    install:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  allow_failures:
  - rust: beta
