source 'https://supermarket.chef.io'

cookbook 'omnibus', git: 'git@github.com:chef-cookbooks/omnibus'
cookbook 'languages', git: 'git@github.com:chef-cookbooks/languages'
cookbook 'delivery-sugar', git: 'git@github.com:chef-cookbooks/delivery-sugar'
cookbook 'artifactory-pro', git: 'git@github.com:chef-cookbooks/artifactory-pro'
cookbook 'oc-artifactory', git: 'git@github.com:chef-cookbooks/oc-artifactory'
cookbook 'opscode-ci', git: 'git@github.com:chef-cookbooks/opscode-ci'
cookbook 'delivery_rust', path: '../cookbooks/delivery_rust'

group :integration do
  cookbook 'apt',      '~> 2.3'
  cookbook 'freebsd',  '~> 0.1'
  cookbook 'yum-epel', '~> 0.3'
end
