source "https://api.berkshelf.com"

metadata

cookbook 'omnibus',
  git: 'https://github.com/chef-cookbooks/omnibus.git'
cookbook 'languages',
  git: 'https://github.com/chef-cookbooks/languages.git'
