source "https://api.berkshelf.com"

metadata

cookbook 'artifactory-pro',
  git: 'git@github.com:chef-cookbooks/artifactory-pro.git',
  branch: 'master'

cookbook 'delivery-sugar',
  git: 'https://github.com/chef-cookbooks/delivery-sugar.git',
  branch: 'master'
