name             'delivery_rust'
maintainer       'adam@getchef.com'
maintainer_email 'adam@getchef.com'
license          'All Rights Reserved'
description      'Installs/Configures delivery_rust'
long_description 'Installs/Configures delivery_rust'
version          '0.3.6'

depends 'apt'
depends 'build-essential'
depends 'omnibus'
depends 'chef-sugar'
depends 'languages'
