source 'https://api.berkshelf.com'

cookbook 'omnibus', github: 'opscode-cookbooks/omnibus', branch: 'tm/all_the_ca_certs'

cookbook 'delivery_rust', path: '../cookbooks/delivery_rust'

# Uncomment to use the latest version of the Omnibus cookbook from GitHub
# cookbook 'omnibus', github: 'opscode-cookbooks/omnibus'

group :integration do
  cookbook 'apt',      '~> 2.3'
  cookbook 'freebsd',  '~> 0.1'
  cookbook 'yum-epel', '~> 0.3'
end
