#!/bin/bash
#
# Perform necessary delivery-cli setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

is_darwin()
{
  uname -v | grep "^Darwin" 2>&1 >/dev/null
}

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if is_darwin; then
  PREFIX="/usr/local"
  mkdir -p "$PREFIX/bin"
else
  PREFIX="/usr"
fi

ln -sf /opt/delivery-cli/bin/delivery $PREFIX/bin || error_exit "Cannot link delivery to $PREFIX/bin"
echo "Thank you for installing delivery-cli!"

exit 0
