#!/bin/bash
#
# Perform necessary delivery-cli removal steps
# after package is uninstalled.
#

# On Redhat based systems, this script is called for the version of
# the package being removed during an upgrade. For an upgrade, $1 == 1,
# for a straight uninstall, $1 == 0.
#
# If we aren't on Redhat OR if this is a straight uninstall, remove
# the symlink from /usr/bin.
if [ ! -e /etc/redhat-release -o "x$1" == "x0" ]; then
  rm -f /usr/bin/delivery-ctl
fi


echo "delivery-cli has been uninstalled!"

exit 0
