#!/bin/bash
#
# Perform necessary delivery-cli removal steps
# after package is uninstalled.
#

is_darwin()
{
  uname -v | grep "^Darwin" 2>&1 >/dev/null
}

if is_darwin; then
  PREFIX="/usr/local"
else
  PREFIX="/usr"
fi

cleanup_symlinks() {
  rm -f $PREFIX/bin/delivery
}

# Clean up binary symlinks if they exist
if [ ! -f /etc/redhat-release -a ! -f /etc/fedora-release -a ! -f /etc/system-release ]; then
  # not a redhat-ish RPM-based system
  cleanup_symlinks
elif [ "x$1" = "x0" ]; then
  # RPM-based system and we're deinstalling rather than upgrading
  cleanup_symlinks
fi

echo "delivery-cli has been uninstalled!"

exit 0
