# Documentation available at https://expeditor.chef.io/

# Slack channel in Chef Software slack to send notifications about build failures, etc
# TEMPORARILY DIABLED. The delivery-cli-notify channel no longer exists, and expeditor has gotten stricter about that.
# TODO: Decide what channel we should be putting these notifications into.
#slack:
#  notify_channel: delivery-cli-notify 

pipelines:
  - verify:
      description: Pull Request validation tests
      env:
        - USE_CHEFDK_LIBS: true

github:
  # Deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Version: Skip Bump"
            - "Expeditor: Skip All"
      - built_in:update_changelog:
          ignore_labels:
            - "Changelog: Skip Update"
            - "Expeditor: Skip All"
